<form class="login-form" action="signin" method="POST">
    <div class="login">
        <div class="form">
            <p>WELCOME</p>
            <span><?= $errorMessages ?? ''; ?></span>
            <label>
                <input type="text" name="email" placeholder="email" />
            </label>
            <label>
                <input type="password" name="password" placeholder="password" />
            </label>
            <button type="submit">login</button>
            <p>
                <a href="signup"> SIGN UP </a>
            </p>
        </div>
    </div>
</form>
<style>
    body {
        background: #e0e0e0;
    }

    span {
        color: red;
        font-family: fantasy;
        font-size: 13px;
        margin: 0 0 15px;
    }

    .login {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
        font-family: 'Rasa Medium', monospace;
        border-radius: 50px;
    }

    .form {
        position: relative;
        z-index: 1;
        border-radius: 10px;
        max-width: 600px;
        margin: auto;
        padding: 45px;
        text-align: center;
        background: #e0e0e0;
        box-shadow:  -11px 11px 22px #395591, 11px -11px 22px #ff0005;
    }

    .form input {
        outline: #fbfbff;
        background: #e0e0e0;
        width: 100%;
        border-radius: 5px;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 20px;
        font-family: 'Rasa Medium', monospace;
    }

    .form input:focus {
        background: #e0e0e0;
    }

    .form button {
        font-family: 'Rasa Medium', monospace;
        text-transform: uppercase;
        outline: 0;
        background: #e0e0e0;
        width: 100%;
        border: 0;
        border-radius: 5px;
        padding: 13px;
        color: navy;
        font-size: 20px;
        cursor: pointer;
    }

    .form a {
        font-family: 'Rasa Medium', monospace;
        text-transform: uppercase;
        outline: 0;
        background: #e0e0e0;
        width: 50%;
        border: 0;
        border-radius: 5px;
        padding: 8px;
        font-weight: bold;
        text-decoration: none;
        color: navy;
        font-size: 13px;
        cursor: pointer;
    }

    .form a:active {
        background: #395591;
    }

    .form button:active {
        background: #395591;
    }
</style>