<div class="login">
    <div class="form">
        <p>WELCOME</p>
        <form class="login-form" action="">
            <label>
                <input type="text" placeholder="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" />
            </label>
            <label>
                <input type="password" placeholder="password" />
            </label>
            <button>login</button>
            <p>
                <a href="./handler/signup.php"> SIGN UP </a>
            </p>
        </form>
    </div>
</div>
<style>
    body {
        background: #e0e0e0;
    }

    .login {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
        font-family: 'Rasa Medium', monospace;
        border-radius: 50px;
    }

    .form {
        position: relative;
        z-index: 1;
        border-radius: 10px;
        max-width: 600px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        background: #e0e0e0;
        box-shadow:  -11px 11px 22px #bebebe, 11px -11px 22px #ffffff;
    }

    .form input {
        outline: none;
        background: #e0e0e0;
        width: 100%;
        border: 0;
        border-radius: 5px;
        margin: 0 0 15px;
        padding: 15px;
        box-sizing: border-box;
        font-size: 20px;
        font-family: 'Rasa Medium', monospace;
    }

    .form input:focus {
        background: #e0e0e0;
    }

    .form button {
        font-family: 'Rasa Medium', monospace;
        text-transform: uppercase;
        outline: 0;
        background: #e0e0e0;
        width: 100%;
        border: 0;
        border-radius: 5px;
        padding: 13px;
        color: navy;
        font-size: 20px;
        cursor: pointer;
    }

    .form a {
        font-family: 'Rasa Medium', monospace;
        text-transform: uppercase;
        outline: 0;
        background: #e0e0e0;
        width: 50%;
        border: 0;
        border-radius: 5px;
        padding: 8px;
        font-weight: bold;
        text-decoration: none;
        color: navy;
        font-size: 13px;
        cursor: pointer;
    }

    .form a:active {
        background: #395591;
    }

    .form button:active {
        background: #395591;
    }
</style>