<form action="" method="POST">
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>


        <label for="email"><b>Email</b></label>
        <span style="color: red"><?php echo $errorMessage['email'] ?? ''; ?></span>
        <input type="text" placeholder="Enter Email" name="email">

        <label for="firstName"><b>First Name</b></label>
        <span style="color: red"><?php echo $errorMessage['firstName'] ?? ''; ?></span>
        <input type="text" placeholder="Enter First Name" name="firstName">

        <label for="lastName"><b>Last Name</b></label>
        <span style="color: red"><?php echo $errorMessage['lastName'] ?? ''; ?></span>
        <input type="text" placeholder="Enter Last Name" name="lastName">

        <label for="surname"><b>Surname</b></label>
        <span style="color: red"><?php echo $errorMessage['surname'] ?? ''; ?></span>
        <input type="text" placeholder="Enter Surname" name="surname">

        <label for="phoneNumber"><b>Phone Number</b></label>
        <span style="color: red"><?php echo $errorMessage['phoneNumber'] ?? ''; ?></span>
        <input type="text" placeholder="Enter Phone Number" name="phoneNumber">

        <label for="psw"><b>Password</b></label>
        <span style="color: red"><?php echo $errorMessage['password'] ?? ''; ?></span>
        <input type="password" placeholder="Enter Password" name="password">
        <hr>

        <button type="submit" class="registerbtn">REGISTER</button>
        <a href="#"> SING IN </a>
    </div>

</form>
<style>
    /** {box-sizing: border-box}*/
    body {
        background: #e0e0e0;
    }
    /* Add padding to containers */
    .container {
        flex-direction: column;
        display: flex;
        position: relative;
        z-index: 1;
        border-radius: 10px;
        max-width: 600px;
        margin: 0 auto 50px;
        padding: 35px;
        background: #e0e0e0;
        box-shadow:  -11px 11px 22px #bebebe, 11px -11px 22px #ffffff;
    }

    label {
        font-size: 13px;
        font-family: fantasy;
        color: #395591;
    }

    /* Full-width input fields */
    input[type=text], input[type=password] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 15px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    h1 {
        font-family: fantasy;
        color: #395591;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 5px;
    }

    /* Set a style for the submit/register button */
    .registerbtn {
        font-family: 'Rasa Medium', monospace;
        text-transform: uppercase;
        outline: 0;
        background: none;
        width: 70%;
        border: 0;
        border-radius: 5px;
        padding: 10px;
        margin: auto;
        font-weight: bold;
        text-decoration: none;
        color: navy;
        font-size: 20px;
        cursor: pointer;
    }

    .registerbtn:active {
        background: #395591;
    }

    .registerbtn:hover {
        opacity:1;
    }

    /* Add a blue text color to links */
    a {
        background: none;
        width: 30%;
        color: navy;
        padding: 8px 15px;
        margin: 10px auto 0;
        border-radius: 10px;
        text-align: center;
        text-decoration: none;
        font-size: 13px;
        cursor: pointer;

    }

    a:active {
        background: #395591;
    }

    /* Set a grey background color and center the text of the "sign in" section */
    .signin {
        background-color: #f1f1f1;
        text-align: center;
    }
</style>
