<form class="products" action="" method="POST">

    <?php foreach ($cartProducts as $product): ?>

        <table>
            <tr>
                <th><?= $product->getProduct()->getName(); ?></th>
                <td>$ <?= $product->getProduct()->getPrice(); ?></td>
                <td><?= $product->getQuantity(); ?></td>
            </tr>
        </table>

    <?php endforeach; ?>

</form>
<style>

    table {
        border-collapse: collapse;
        background: #e0e0e0;
        border: 4px solid #000;
        margin: 20px;
    }
    td, th {
        padding: 5px;
        border: 2px solid black;
        color: black;
        height: 40px;
        width: 300px;
    }


</style>