<div class="container_product">
    <div class="products">
        <div class="product">
            <div class="image">
                <img src="https://prostoreshop.ru/wp-content/uploads/2022/05/smartfon-apple-iphone-11-64gb-global-chernyj-7.jpg" alt="">
            </div>
            <div class="namePrice">
                <h3>Iphone</h3>
                <span>$ 1000</span>
            </div>
            <p>L</p>
            <div class="stars">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>
            <div class="bay">
                <button> bay now </button>
            </div>
        </div>
        <div class="product">
            <div class="image">
                <img src="https://prostoreshop.ru/wp-content/uploads/2022/07/smartfon-samsung-galaxy-a13-3-32-gb-chernyj.jpg" alt="">
            </div>
            <div class="namePrice">
                <h3>Sumsung</h3>
                <span>$ 800</span>
            </div>
            <p>L</p>
            <div class="stars">
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-solid fa-star"></i>
                <i class="fa-regular fa-star"></i>
            </div>
            <div class="bay">
                <button> bay now </button>
            </div>
        </div>
    </div>
</div>
<style>
    :root{
        --bodyBack: #ffeaed;
        --textColor: #1b2741;
        --starColor: #f67034;
        --sectionBack: #f7f6f9;
    }

    .container_product{
        width: 80vw;
        height: 80vh;
        display: flex;
        flex-direction: column;
        justify-content: space-around;
    }

    .products{
        width: 100%;
        align-self: center;
        height: 70%;
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        gap: 40px;
    }
    .product{
        position: relative;
        background-color: var(--sectionBack);
        width: 350px;
        height: 100%;
        box-shadow: -11px 11px 22px blue, 11px -11px 22px red;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding: 20px 20px 40px;
        border-radius: 10px;
        transition: .3s;
    }
    .product:hover{
        transform: translateY(-15px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
    }
    .image{
        width:100%;
        height: 60%;
        display: grid;
        place-content: center;
    }
    .image img{
        width: 240px;
    }
    .namePrice{
        width: 100%;
        display: flex;
        justify-content: space-between;
    }
    .namePrice h3{
        font-size: 20px;
        text-transform: capitalize;
        color: var(--textColor);
    }
    .namePrice span{
        font-size: 13px;
        color: var(--starColor);
    }
    .product p{
        font-size: 20px;
        line-height: 20px;
        color: black;
    }
    /*.stars svg{*/
    /*    font-size: 10px;*/
    /*    color: var(--starColor);*/
    /*}*/
    .bay{
        position: absolute;
        bottom: 20px;
        right: 20px;
    }
    .bay button{
        padding: 10px 20px;
        border-radius: 7px;
        border: none;
        background-color: var(--textColor);
        color: var(--sectionBack);
        font-size: 18px;
        text-transform: capitalize;
        cursor: pointer;
        transition: .5s;
    }
    .bay button:hover{
        transform: scale(1.1);
    }
</style>