<div class="cart" id="quantity">
    <img src="https://cdn-icons-png.flaticon.com/512/263/263142.png" alt="">
    <span class="qty"><?= $quantity; ?></span>
</div>
<div class="container_product">

    <div class="products">
        <?php foreach ($products as $product): ?>
            <div class="product">
                <div class="image">
                    <img src="<?= $product->getImg(); ?>" alt="">
                </div>
                <div class="namePrice">
                    <h3><?= $product->getName(); ?></h3>
                    <h4>$ <?= $product->getPrice(); ?></h4>
                </div>
                <p></p>
                <form class="my-form" action="/add" method="POST" id="myForm">
                    <div class="bay">
                        <input type="hidden" id="productId" name="productId" value=<?= $product->getId(); ?>>
                        <input type="hidden" id="categoryId" name="categoryId" value="<?= $categoryId; ?>">
                        <button type="submit" id="butn">Add to cart</button>
                    </div>
                </form>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script
        src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
        crossorigin="anonymous"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('.my-form button').click(function (){
            var parent = $(this).parent();
            var categoryId = parent.find("[name='categoryId']").attr('value');
            var productId = parent.find("[name='productId']").attr('value');
            $.post( "/add", {categoryId: categoryId, productId: productId}, function( data ) {
                $('.qty').html(data);
            });
            return false;
        });
    });


</script>

<style>
    .cart img {
        color: white;
        width: 25px;
        height: 25px;
    }
    .cart span {
        color: black;
        position: relative;
        width: 30px;
        height: 20px;
        top: -8px;
        right: 5px;
        text-align: center;
        font-size: 12px;
        padding: 6px;
        border-radius: 50%;
    }

    :root{
        --bodyBack: #ffeaed;
        --textColor: #1b2741;
        --sectionBack: #f7f6f9;
    }

    .container_product{
        width: 80vw;
        height: 80vh;
        display: flex;
        flex-direction: column;
        justify-content: space-around;
    }

    .products{
        width: 100%;
        align-self: center;
        height: 70%;
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        gap: 40px;
    }

    .product{
        position: relative;
        background-color: var(--sectionBack);
        width: 350px;
        height: 100%;
        box-shadow: -11px 11px 22px gray, 11px -11px 22px gray;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        padding: 20px 20px 40px;
        border-radius: 10px;
        transition: .3s;
        flex-wrap: wrap;
    }
    .product:hover{
        transform: translateY(-15px);
        box-shadow: 0 5px 10px rgba(0, 0, 0, .2);
    }
    .image{
        width:100%;
        height: 60%;
        display: grid;
        place-content: center;
    }
    .image img{
        width: 240px;
    }
    .namePrice{
        width: 100%;
        display: flex;
        justify-content: space-between;
    }
    .namePrice h3{
        font-size: 20px;
        text-transform: capitalize;
        color: var(--textColor);
    }
    .namePrice h4{
        font-size: 20px;
        text-transform: capitalize;
        color: #ff7314;
    }
    .product p{
        font-size: 20px;
        line-height: 100px;
        color: black;
    }

    .bay{
        position: absolute;
        bottom: 20px;
        right: 20px;
    }
    .bay button{
        padding: 10px 20px;
        border-radius: 7px;
        border: none;
        background-color: var(--textColor);
        color: var(--sectionBack);
        font-size: 18px;
        text-transform: capitalize;
        cursor: pointer;
        transition: .5s;
        text-decoration: none;
    }
    .bay button:hover{
        transform: scale(1.1);
    }

    /*.go {*/
    /*    background: #395591;*/
    /*    width: 5%;*/
    /*    color: navy;*/
    /*    padding: 8px 15px;*/
    /*    margin: 10px auto 0;*/
    /*    border-radius: 10px;*/
    /*    text-align: center;*/
    /*    text-decoration: none;*/
    /*    font-size: 13px;*/
    /*    cursor: pointer;*/
    /*}*/
</style>
